#!/bin/zsh

set -ex

pushd ~/.zprezto

git fetch upstream
git checkout master
git merge -m "Merge upstream/master" upstream/master
git submodule update --init --recursive

cd contrib
for dir in $(fd -t directory --exact-depth=1); do
  pushd $dir
  git pull
  popd
done

popd
