#!/bin/zsh

set -ex

OLDDIR=$PWD
cd ~/.zprezto

git fetch upstream
git checkout master
git merge -m "Merge upstream/master" upstream/master
git submodule update --init --recursive

cd ~/.zprezto/contrib/fzf-tab
git pull

cd $OLDDIR
